### ISSUE TITLE
Crash when crafting Thamucraft greatwood planks [The game crashed whilst rendering screen]

### ISSUE THREAD

**Issue by Nick-McKay** [Vazkii/Patchouli#135]
I've been able to reproduce this crash countless times. If I go to a magical forest in a new world, break an oak block off a tree, craft oak planks, craft a stick, break a greatwood log block, and attempt to craft greatwood planks, my game crashes. The error is: 
"The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Rendering screen"

My only mods are cubic chunks (which shouldn't effect this?), the latest thaumcraft release, baubles, and patchouli.

And the full crash log is attached:
[crash-2019-06-08_20.59.18-client.txt](https://github.com/Vazkii/Patchouli/files/3269072/crash-2019-06-08_20.59.18-client.txt)

**Comment by xenthe** [comment]
If you want to reproduce the crash yourself, the seed is 581145023053873480, I teleport immediately to 10000, 100, 10000 in creative mode, switch to survival at the ground, collect the oak log from the nearby oak tree, then craft planks and sticks, then collect a greatwood log from the nearby greatwood tree, attempt to do the same crafting steps, and then the game crashes. This occurs on many forge releases.

**Comment by drizzs** [comment]
does the issue happen without patchouli?

**Comment by xenthe** [comment]
No, it does not. Though, I've come to learn that installing FastWorkbench does eliminate the issue.

**Comment by drizzs** [comment]
All my rendering issues happen with patchouli...

**Comment by KokSaker** [comment]
It's an old issue. I've been using the fastworkbench with the vanilla recipe book disabled, this seem to fix the crash, at least I didn't have it happen to me for a month now.
Now with the more recent personal modpack that I didn't disable the recipe book(because why would I want to do this otherwise) I've got this crash - https://gist.github.com/KokSaker/d87f399be1593df17155d42afb6de6c8 again. Similar issue here https://github.com/Vazkii/Patchouli/issues/126
