### ISSUE TITLE
Unsure if intended but recipe seems to use name of the recipe file

### ISSUE THREAD

**Issue by RobertSkalko** [Vazkii/Patchouli#14]
My recipe for an item didn't work even though i put the correct id in the recipe field, and i found that i wasn't supposed to put the id but the recipe file name instead (or both have to match). I changed the file name to match the id and it worked.

Sorry if this was in the wiki.

**Comment by Daomephsta** [comment]
It sounds like you're expecting the ID of a vanilla recipe to be the ID of the item it produces, is this correct?
If so, firstly, recipes are vanilla, Patchouli has nothing to do with loading them.
And secondly, recipes use their path relative to the recipes directory as their ID, because it is possible and valid to have multiple recipes for the same item.

**Comment by RobertSkalko** [comment]
Sorry then, i'm closing.
