### ISSUE TITLE
Maven Release 1.16-37 for Fabric

### ISSUE THREAD

**Issue by alexis-evelyn** [Vazkii/Patchouli#269]
The release at https://maven.blamejared.com/vazkii/patchouli/Patchouli/1.16-37/Patchouli-1.16-37.jar does not include fabric.mod.json which makes it difficult to have Fabric remap the jar for mod development.

I'm currently having to use https://maven.blamejared.com/vazkii/patchouli/Patchouli_1.16-fabric/1.16-37.21-FABRIC/Patchouli_1.16-fabric-1.16-37.21-FABRIC.jar in order to be able to use the mod in my development environment.

This specifically makes it where I can use the api itself in Java, but am unable to load the Patchouli mod when running the Minecraft development client.

**Comment by williewillus** [comment]
sorry our Maven has been an absolute mess, we've been sorting it out and hopefully things will be a lot clearer going forward.

first, the folder to use is now https://maven.blamejared.com/vazkii/patchouli/Patchouli/ for both forge and fabric. There were separate folders in the past, but that was due to a configuration mistake.

Second, Fabric builds have a -FABRIC suffix. So the 1.16-37 build you were trying to use was actually the Forge version.

I updated the READMEs of both branches to more clearly state what the current versioning/naming strategy is and how to get builds. Hope it helps! https://github.com/Vazkii/Patchouli/blob/1.16-fabric/README.md#maven-info

If you have any more questions join Discord and ask in #patchouli
