### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ayushaanand** [Vazkii/Patchouli#282]
I have optifine installed and when i installed patchuouli it crashes with rendering error. please make patcuouli optifabric compatible.

**Comment by williewillus** [comment]
optifine is not supported

**Comment by ayushaanand** [comment]
but why?

**Comment by williewillus** [comment]
Optifine is a closed-source mod. No one knows what it's really doing, and issues with it are pretty much impossible to debug. Not to mention you're using Optifabric, which is an additional layer of hacks to graft it onto Fabric. There's nothing I can do.

Since you're on Fabric I would recommend just switching to other performance mods like Phosphor/Lithium/Sodium

**Comment by ayushaanand** [comment]
ok but i am using optifabric only for those shaders
